### ISSUE TITLE
.t sucks, bring back .tz

### ISSUE THREAD

**Issue by cbirkett** [jinpark/common-bot#16] opened 2014-04-18 16:28 UTC
12:26:53 <~cbirkett> .t japan
12:26:54 @common I'm sorry, I don't know about the japan timezone or user.

Should return results from more input formats like country name, time zone (e.g. "edt"), etc.

**Comment by vertigoacid** [comment] 2014-04-18 16:38
To add some detail to this otherwise useless post, the problem is having to specify a tzdata style timezone, e.g Asia/Tokyo, instead of it being able to do a lookup against a PST/EST/etc style name or a geographical location.

**Comment by jinpark** [comment] 2014-04-19 05:00
So I looked up how hard it would be to do 'est' etc stuff and that shit is annoying. Theres an EST in NA and an EST in Australia and other stupid stuff like that. So I'm doing that unless theres a good reason to. I'll have it recognize locations though

**Comment by cbirkett** [comment] 2014-04-19 05:02
That's fine.

**Comment by jinpark** [comment] 2014-04-19 05:29
Bob seem happy (or as happy as bob can be)

**Comment by jinpark** [comment] 2014-05-07 19:55
Reopening since I broke it again

**Comment by jinpark** [comment] 2014-06-30 22:22
Er, no one complained about this afaik so I'm closing

**Closed as completed by jinpark** 2014-06-30 22:22 UTC
